### ISSUE TITLE
Kord builder should probably not be a suspend function

### ISSUE THREAD

**Issue by danielesegato** [kordlib/kord#734] opened 2022-12-04 10:07 UTC
Hey guys, thanks for your lib.

I just want to spawn a discussion here about the API design.

I'm not sure I share the decision of making the Kord initialization require a coroutine.

Maybe the initialization should be a separate step?

**Comment by DRSchlaubi** [comment] 2023-06-15 19:23
Duplicate of #146

**Closed by DRSchlaubi** 2023-06-15 19:23 UTC
