### ISSUE TITLE
Support delta events for voice channels

### ISSUE THREAD

**Issue by daymxn** [kordlib/kord#882] opened 2023-10-02 16:44 UTC
Currently, you have to do some inspections on `VoiceStateUpdateEvent` to figure out the specifics behind a user's interaction with a Voice Channel- which is a bit verbose for more simple needs; such as listening for when someone joins or leaves a voice channel.

Adding additional events to support more fine grained delta events like `VoiceChannelJoinedEvent` and `VoiceChannelLeftEvent` would be of great help here.

For example, this is what I'm currently using in my project:

```kotlin
class VoiceChannelExtension : Extension() { 
  override val name = "VoiceChannelExtension"

  override suspend fun setup() {
    event<VoiceStateUpdateEvent> {
      action { 
        val oldChannel = event.old
        val newChannel = event.state
          
        if (oldChannel?.channelId != null) {
          if (newChannel.channelId != null) {
            if (newChannel.channelId != oldChannel.channelId) {
              bot.send(VoiceChannelJoinedEvent(newChannel))
              bot.send(VoiceChannelLeftEvent(oldChannel))
            }
          } else {
            bot.send(VoiceChannelLeftEvent(oldChannel))
          }
        } else { 
          bot.send(VoiceChannelJoinedEvent(newChannel))
        }
      }
    } 
  }
}

data class VoiceChannelJoinedEvent(val channel: VoiceState) : KordExEvent
data class VoiceChannelLeftEvent(val channel: VoiceState) : KordExEvent
```

**Comment by DRSchlaubi** [comment] 2023-10-02 16:47
actually kord doesn't have these kinda events by design, because they often require the old version to be cached, maybe @gdude2002 would be interested in adding this to kordex?

**Comment by gdude2002** [comment] 2023-10-02 17:19
Call it, haha

Yeah, this is the kind of thing KordEx intends to provide, so I don't see why not. If someone sticks an issue there then I can look into it.

**Comment by DRSchlaubi** [comment] 2023-10-02 19:42
Alrighty then I'll close this

**Closed by DRSchlaubi** 2023-10-02 19:42 UTC
