### ISSUE TITLE
Update documentation for Components

### ISSUE THREAD

**Issue by MrDiamondDog** [kordlib/kord#846] opened 2023-07-15 21:44 UTC
There is a complete blank area where documentation for components should be. This makes it impossible to figure out how to use them.

https://github.com/kordlib/kord/wiki/Interactions#components

![image](https://github.com/kordlib/kord/assets/84212701/954655e5-2994-451a-bdc5-19989c5d9ecc)

**Comment by DRSchlaubi** [comment] 2023-07-15 21:48
Duplicate of #11

Also a new wiki is in the works

**Closed by DRSchlaubi** 2023-07-15 21:48 UTC
