### ISSUE TITLE
Exception when forcefully killing process in linux

### ISSUE THREAD

**Issue by EduardAblekimov** [kordlib/kord#92] opened 2020-10-19 11:17 UTC
Process is started using builded jar. Then killed with `pkill -f 'java -jar'`. After that, the following exception is thrown. It's not really breaks functionality or something, since i kill process anyway, but I don't think it should be there either (good thing to remove from CI log)

```
root@2zvn: pkill -f 'java -jar'                                                                       
Exception in thread "main" java.lang.ClassCastException: class com.gitlab.kordlib.gateway.State$Detached cannot be cast to class com.gitlab.kordlib.gateway.State$Running (com.gitlab.kordlib.gateway.State$Detached and com.gitlab.kordlib.gateway.State$Running are in unnamed module of loader 'app')                                                         
        at com.gitlab.kordlib.gateway.DefaultGateway$start$2.invokeSuspend(DefaultGateway.kt:143)                                  
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                  
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)                                                    
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)                                               
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)                                  
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)                                                             
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)                                   
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)                          
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)                            
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)   
```

**Comment by BartArys** [comment] 2020-10-19 11:45
Thanks for reporting this issue!
We're internally aware of the issue. The [line itself](https://github.com/kordlib/kord/blob/master/gateway/src/main/kotlin/com/gitlab/kordlib/gateway/DefaultGateway.kt#L143) is correct, but the resulting bytecode (generated through [kotlinx.atomicfu](https://github.com/Kotlin/kotlinx.atomicfu)) seems to erroneously assume the state to only be `State.Running`.

It's a bit of a tricky thing to test (since gateway connects are heavily rate limited and we can't really mock anything without risk of changing the bytecode) and given the situations you encounter the exception in, it has taken a place on the back burner. I'm sure that a bit of fiddling with the code will get it solved though, but a permanent fix would include making a minimal reproducible example and reporting it to the kotlix.atmocfu people.

**Comment by HopeBaron** [comment] 2023-02-16 13:16
Closed as this has been opened since 2yrs and there is no update on it.

**Closed by HopeBaron** 2023-02-16 13:16 UTC
